name = "dreamlab-nostr-relay"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-01"

[build]
command = "worker-build --release"

[vars]
RELAY_NAME = "DreamLab Nostr Relay"
ADMIN_PUBKEYS = "a617d2109bdd3f1a607d5a837e885178f6367af296885d7f058c26b2bd03221a,11ed64225dd5e2c5e18f61ad43d5ad9272d08739d3a20dd25886197b0738663c,37f922fd632060ee9905505b687f8803090e943ffe92105428b3859a1c4ee7ff"
ALLOWED_ORIGIN = "https://dreamlab-ai.com"

[[d1_databases]]
binding = "DB"
database_name = "dreamlab-relay"
database_id = "97c77d23-0e24-4325-ada7-1747eab4095b"

[durable_objects]
bindings = [
  { name = "RELAY", class_name = "NostrRelayDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NostrRelayDO"]

[triggers]
crons = ["*/5 * * * *"]
