#!/usr/bin/env bash
# Content-generator inventory — dream-cycle evaluator entrypoint.
#
# `content-generators` was a named scan surface on the site-build-content deep
# with no executing edge behind it: the 2026-09-05 probe recorded "Degraded — no
# observations supplied", so five nights reasoned about generators no evaluator
# had ever looked at. That is 09-04's own lesson (a named surface with no
# receipt is worse than no surface). This gives the surface a receipt.
#
# The counts are SURFACE-DEPENDENT, not hard-coded: each expected value is
# re-derived from the generator's own inputs and compared against the committed
# artefact. Both artefacts (src/data/workshop-list.json, src/data/testimonials.json)
# are tracked in git but regenerated by the `prebuild` hook, so a source edit
# committed without a regenerate leaves stale JSON on main — the drift this
# catches. Adding a workshop directory or a testimonial changes the expected
# numbers automatically; nothing here needs editing when content changes.
#
# Invariants, straight from the generators:
#   generate-workshop-list.mjs  — every non-dot directory under
#     public/data/workshops/ yields exactly one workshop-list.json entry and one
#     manifest.json, whose `pages` enumerate that directory's *.md files.
#   generate-testimonials.mjs   — src/data/testimonials.json equals
#     content/site-content.yaml at pages.testimonials.items.
#
# Emits CONTENT-GENERATORS-OK / CONTENT-GENERATORS-FAIL and exits non-zero on
# FAIL. Must be invoked quote-free from dream.config.json (the annexe ssh
# dispatch strips nested double quotes, so no logic may be inlined there).
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1
exec node scripts/lib/content-generators.mjs
